### ISSUE TITLE
fsnotify v1.5.0 and GOOS=freebsd does not build

### ISSUE THREAD

**Issue by xyproto** [fsnotify/fsnotify#389]
`GOOS=freebsd go` build works with Go 1.17 and fsnotify v1.4.9, but stops working with fsnotify v1.5.0.

The error message is:

```
vendor/github.com/fsnotify/fsnotify/kqueue.go:193:43: undefined: unix.O_SYMLINK
```

**Comment by nathany** [comment]
Thanks for the report.

Confirmed that changes in 1.5.0 via #289 began using `unix.O_SYMLINK` which is defined for Darwin (macOS) [zerrors_darwin_amd64.go](https://cs.opensource.google/go/x/sys/+/master:unix/zerrors_darwin_amd64.go;l=1138) but not for FreeBSD or other BSDs.

/cc @Code0x58

**Comment by nathany** [comment]
Of note, we don't have FreeBSD as a GitHub runner, because they only supports Linux, Windows, and macOS. They do support custom runners as one possibility. Or we may be able to use the the same trick that #371 is using for Solaris?
https://github.com/papertigers/illumos-vm

I don't currently have a FreeBSD environment set up -- I was using Vagrant before, but I haven't worked with it for a while.
https://github.com/nathany/vagrant-gopher

**Comment by nshalman** [comment]
> Of note, we don't have FreeBSD as a GitHub runner, because they only supports Linux, Windows, and macOS. They do support custom runners as one possibility. Or we may be able to use the the same trick that #371 is using for Solaris?

See https://github.com/vmactions/freebsd-vm

**Comment by nathany** [comment]
v1.5.1 reverts the changes from 1.5.0, but lets leave this open to review.

**Comment by nathany** [comment]
I do not have BSD to test on. Please report back whether 1.5.1 resolved the issue.

**Comment by r-darwish** [comment]
Ran `go test` on FreeBSD 13 with Go 1.17 on the main branch. All tests passed

**Comment by nshalman** [comment]
@r-darwish Any chance you could help me write a github action that uses https://github.com/vmactions/freebsd-vm similar to the one I'm working on for illumos (see https://github.com/nshalman/fsnotify/commit/96066fd2575e3fa1fc8510d4cd0cbcb021337a05) to run the tests on FreeBSD?

It would be great to be able to catch these things in the future, even if we have to trigger the tests manually because they're too slow to run on every push/pr.

**Comment by r-darwish** [comment]
https://github.com/fsnotify/fsnotify/pull/419

**Comment by nshalman** [comment]
It occurs to me that cross-compilation builds might also have caught this.
I'm still very glad to be able to run the full tests on FreeBSD thanks to #419.
