### PR TITLE
Add FreeBSD testing in Github Actions (fix #389)

### LINKED ISSUE #389: fsnotify v1.5.0 and GOOS=freebsd does not build
`GOOS=freebsd go` build works with Go 1.17 and fsnotify v1.4.9, but stops working with fsnotify v1.5.0.

The error message is:

```
vendor/github.com/fsnotify/fsnotify/kqueue.go:193:43: undefined: unix.O_SYMLINK
```

### PR DESCRIPTION
**Pull request by r-darwish**
Fix #389

### CODE REVIEW

**Comment by nshalman** [comment]
Thank you!!
It looks like that test [took about 5 minutes to run](https://github.com/r-darwish/fsnotify/runs/4844833573?check_suite_focus=true). My only question is whether we want that on every push or if we want to just give maintainers the option to run them manually.
Either way, this is fantastic to have and I look forward to some version of it landing soon!

**Comment by r-darwish** [comment]
Yeah, the reason for being slow is that it downloads a full VM image, extract it and boots it up before doing anything. I think 5 minutes are bearable, though

**Review by nathany — APPROVED** [review]

**Comment by nshalman** [comment]
I wonder if there's a clever way to make it somehow depend on the cross-compilation target so that if it wouldn't build we won't waste time spinning up the VM for testing...

**Comment by nathany** [comment]
Well, if we do `needs: build`, it will run sequentially instead of in parallel...

**Comment by nshalman** [comment]
The builds are very fast. I see the argument on the other side though.

**Comment by nathany** [comment]
That the VM build starts later? Maybe more waiting

**Comment by nathany** [comment]
How can we get builds to run on external pull requests like this?

We don't have any secrets to worry about leaking.

**Comment by nshalman** [comment]
> How can we get builds to run on external pull requests like this?
> 
> We don't have any secrets to worry about leaking.

😄  #415 should do it. Alternately we could favor `pull_request` over `push` though I do still prefer both.

**Comment by nshalman** [comment]
Given @nathany's approval I think we should merge this. If the build times become onerous we can revisit moving them out to the forthcoming slow-tests that I'm planning for illumos. Better to err on the side of testing.
