### PR TITLE
rm go1.5.4 from travis config since the linter doesn't build in 1.5

### PR DESCRIPTION
**Pull request by pattyshack**

### CODE REVIEW

**Comment by nathany** [comment]
Thanks.

Out of curiosity, what error occurred when the linter didn't build? I'm a bit surprised over the issue.

**Comment by nathany** [comment]
Oh, I see.

```
# github.com/golang/lint
../../golang/lint/lint.go:249: undefined: types.ImportMode
```
from https://travis-ci.org/fsnotify/fsnotify/jobs/165118920

There is a closed issue with a similar error https://github.com/golang/lint/issues/246
